# Generated by Django 5.2.6 on 2025-09-05 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_id",
                    models.CharField(max_length=10, unique=True, verbose_name="รหัสห้อง"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อห้อง")),
                ("capacity", models.IntegerField(verbose_name="ความจุ")),
                (
                    "max_booking_hours",
                    models.PositiveIntegerField(
                        default=1, verbose_name="จำนวนชั่วโมงที่จองได้สูงสุด"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="สถานะเปิด/ปิด"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField(verbose_name="วันที่จอง")),
                ("start_time", models.TimeField(verbose_name="เวลาเริ่มต้น")),
                ("end_time", models.TimeField(verbose_name="เวลาสิ้นสุด")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้จอง",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.room",
                        verbose_name="ห้องที่จอง",
                    ),
                ),
            ],
            options={
                "unique_together": {("room", "booking_date", "start_time")},
            },
        ),
    ]
